[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "博雅正链隐私计算框架YAPE"
authors = [{name = "YAPE", email = "heyifei@pku.edu.cn"}]
dynamic = ["version", "description"]
